
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.platform.com
  resources:
  - stackinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.platform.com
  resources:
  - stackinstances/finalizers
  verbs:
  - update
- apiGroups:
  - app.platform.com
  resources:
  - stackinstances/status
  verbs:
  - get
  - patch
  - update
