# permissions for end users to edit stackinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackinstance-editor-role
rules:
- apiGroups:
  - app.platform.com
  resources:
  - stackinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.platform.com
  resources:
  - stackinstances/status
  verbs:
  - get
