# permissions for end users to edit platforminstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platforminstance-editor-role
rules:
- apiGroups:
  - app.platform.com
  resources:
  - platforminstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.platform.com
  resources:
  - platforminstances/status
  verbs:
  - get
